version: '3.8'
services:
  app:
    container_name: online_classroom_pens_api
    restart: always
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: .
        target: /usr/src/app
      - /usr/src/app/node_modules/
    ports:
      - 3000:3000

  # nginx:
  #   image: 1.25.2-alpine
  #   restart: always
  #   volumes:
  #     - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  #   ports:
  #     - 80:80
  #   depends_on:
  #     - app

  nginx_proxy_manager:
    container_name: online_classroom_pens_nginx_proxy_manager
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt

  postgresql:
    container_name: online_classroom_pens_db
    image: postgres:16.0-alpine3.18
    env_file:
      - .env
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  ignore:
  db-data:
    driver: local
