version: '3.8'
services:
  # app:
  #   container_name: online_classroom_pens_api
  #   restart: always
  #   env_file:
  #     - .env.staging
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   volumes:
  #     - ./public:/app/public
  #   ports:
  #     - 3000:3000

  postgresql:
    container_name: online_classroom_pens_db
    image: postgres:16.0-alpine3.18
    env_file:
      - .env.staging
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./data:/data
    networks:
      - redis-net

volumes:
  nginx-data:
    driver: local
  db-data:
    driver: local
